## Imports

In [2]:
import sys
sys.path.append("..")

import pandas as pd
from datacleaner import DataCleaner

## Instancia del objeto `cleaner` + dataset de prueba

In [5]:
df = pd.read_csv("ventas.csv")
df.set_index("id_venta", inplace=True)

cleaner = DataCleaner(df)
cleaner.get_summary()

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  📋  DataFrame
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Filas               3,035
  Columnas            5
  Nulos totales       4
  Duplicados          35

──────────────────────────────────────────────────────────────────────
  Columna                   Tipo           Únicos    Nulos    % nulos
──────────────────────────────────────────────────────────────────────
  producto                  str                30        0      0.00%
  precio                    str             2,590        2      0.07% ⚠️
  cantidad                  float64            12        2      0.07% ⚠️
  fecha_venta               str               364        0      0.00%
  categoria                 str                 3        0      0.00%

────────────────────────────────────────────────────────────
  Filas duplicadas: 35 ⚠️

────────────────────────────────────────────────────────────
  Primeras 5 filas:

                   producto   precio  cantidad fecha_venta          categoria
id_venta
792       Cuadro decorativo   $69.94       5.0  02/01/2024         Decoración
811         Lámpara de mesa  $105.10       5.0  02/01/2024         Decoración
1156               Secadora   $97.96       3.0  02/01/2024  Electrodomésticos
1372               Heladera  $114.35       8.0  02/01/2024  Electrodomésticos
1546               Secadora  $106.21       4.0  02/01/2024  Electrodomésticos

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

## Datos nulos

In [6]:
cleaner.display_nulls()

                       producto precio  cantidad fecha_venta    categoria
id_venta
627       Elementos de cerámica    NaN       NaN  17/01/2024   Decoración
2171        Parlantes Bluetooth    NaN       NaN  17/01/2024  Electrónica

In [7]:
cleaner.clean_nulls(delete=True)

Datos nulos correctamente eliminados

## Datos duplicados

In [8]:
cleaner.clean_dups()

Filas completamente duplicadas: 70
Filas con index duplicado: 70
¿Coinciden? True
 --------------------------------------------------------------------------------
Filas restantes: 2998
Index duplicados restantes: 0

## Corrección de tipos de datos

In [9]:
cleaner.cast_columns(columns=["cantidad"], to="int64")
cleaner.cast_columns(columns=["precio"], to="float64")
cleaner.cast_columns(columns=["fecha_venta"], to="datetime")
cleaner.cast_columns(columns=["producto"], to="category")
cleaner.cast_columns(columns=["categoria"], to="category")

✓ 'cantidad' convertida correctamente → int64
✓ 'precio' convertida correctamente → float64
✓ 'fecha_venta' convertida correctamente → datetime64[us]
✓ 'producto' convertida correctamente → category
✓ 'categoria' convertida correctamente → category

In [10]:
cleaner.df.dtypes

producto             category
precio                float64
cantidad                int64
fecha_venta    datetime64[us]
categoria            category
dtype: object

## Verificación de outliers

In [11]:
cleaner.display_outliers(columns=["precio", "cantidad"], method="iqr")

✅ No se detectaron outliers en las columnas.

## Guardar instancia del DataFrame del `cleaner` en un nuevo elemento

In [ ]:
df_clean = cleaner.df.copy()